//
//  ScrollViewController.swift
//  ISMOriginalWork
//
//  Created by Gauri Pala on 10/31/20.
//  Copyright © 2020 Gauri Pala. All rights reserved.
//

import UIKit
import Foundation
import SafariServices

class ScrollViewController: UIViewController{
    
   
    @IBOutlet weak var defBtn: UIButton!
    var isOpen = true
    var isOpen2 = true
    var isOpen3 = true
    @IBOutlet weak var effBtn: UIButton!
    @IBOutlet weak var statBtn: UIButton!
    @IBOutlet weak var fiveBtn: UIButton!
    @IBOutlet weak var bikeBtn: UIButton!
    @IBOutlet weak var waterBtn: UIButton!
    @IBOutlet weak var foodBtn: UIButton!
    @IBOutlet weak var eneBtn: UIButton!
    @IBOutlet weak var clothBtn: UIButton!
    @IBOutlet weak var moreInfoIssueBtn: UIButton!
    @IBOutlet weak var moreTipsBtn: UIButton!
    @IBOutlet weak var calcBtn: UIButton!
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        defBtn.layer.cornerRadius = 20
        defBtn.layer.shadowColor = UIColor.black.cgColor
        defBtn.layer.shadowOffset = CGSize(width: 5, height: 5)
        defBtn.layer.shadowRadius = 5
        defBtn.layer.shadowOpacity = 0.07
        defBtn.titleLabel?.numberOfLines = 4
        defBtn.titleLabel?.adjustsFontSizeToFitWidth = true
        defBtn.titleLabel?.lineBreakMode = NSLineBreakMode.byClipping
        defBtn.titleLabel?.textAlignment = .center
        
        effBtn.layer.cornerRadius = 20
        effBtn.layer.shadowColor = UIColor.black.cgColor
        effBtn.layer.shadowOffset = CGSize(width: 5, height: 5)
        effBtn.layer.shadowRadius = 5
        effBtn.layer.shadowOpacity = 0.07
        effBtn.titleLabel?.numberOfLines = 6
        effBtn.titleLabel?.adjustsFontSizeToFitWidth = true
        effBtn.titleLabel?.lineBreakMode = NSLineBreakMode.byClipping
        effBtn.titleLabel?.textAlignment = .center
        
        statBtn.layer.cornerRadius = 20
        statBtn.layer.shadowColor = UIColor.black.cgColor
        statBtn.layer.shadowOffset = CGSize(width: 5, height: 5)
        statBtn.layer.shadowRadius = 5
        statBtn.layer.shadowOpacity = 0.07
        statBtn.titleLabel?.numberOfLines = 7
        statBtn.titleLabel?.adjustsFontSizeToFitWidth = true
        statBtn.titleLabel?.lineBreakMode = NSLineBreakMode.byClipping
        statBtn.titleLabel?.textAlignment = .center
        
        fiveBtn.layer.cornerRadius = 73
        fiveBtn.layer.shadowColor = UIColor.black.cgColor
        fiveBtn.layer.shadowOffset = CGSize(width: 5, height: 5)
        fiveBtn.layer.shadowRadius = 5
        fiveBtn.layer.shadowOpacity = 0.07
        
        
        bikeBtn.layer.cornerRadius = 73
        bikeBtn.layer.shadowColor = UIColor.black.cgColor
        bikeBtn.layer.shadowOffset = CGSize(width: 5, height: 5)
        bikeBtn.layer.shadowRadius = 5
        bikeBtn.layer.shadowOpacity = 0.07
        
        waterBtn.layer.cornerRadius = 73
        waterBtn.layer.shadowColor = UIColor.black.cgColor
        waterBtn.layer.shadowOffset = CGSize(width: 5, height: 5)
        waterBtn.layer.shadowRadius = 5
        waterBtn.layer.shadowOpacity = 0.07
        
        eneBtn.layer.cornerRadius = 73
        eneBtn.layer.shadowColor = UIColor.black.cgColor
        eneBtn.layer.shadowOffset = CGSize(width: 5, height: 5)
        eneBtn.layer.shadowRadius = 5
        eneBtn.layer.shadowOpacity = 0.07
        
        foodBtn.layer.cornerRadius = 73
        foodBtn.layer.shadowColor = UIColor.black.cgColor
        foodBtn.layer.shadowOffset = CGSize(width: 5, height: 5)
        foodBtn.layer.shadowRadius = 5
        foodBtn.layer.shadowOpacity = 0.07
        
        clothBtn.layer.cornerRadius = 73
        clothBtn.layer.shadowColor = UIColor.black.cgColor
        clothBtn.layer.shadowOffset = CGSize(width: 5, height: 5)
        clothBtn.layer.shadowRadius = 5
        clothBtn.layer.shadowOpacity = 0.07
        
        moreTipsBtn.layer.cornerRadius = 20
        moreInfoIssueBtn.layer.cornerRadius = 20
        calcBtn.layer.cornerRadius = 20
        
        
        
        
        
       
    }
    
    @IBAction func calcTap(_ sender: Any) {
        showSafariVC(for: "https://www3.epa.gov/carbon-footprint-calculator/")
    }
    
    
    @IBAction func defBtnTap(_ sender: Any) {
        if isOpen{
            isOpen = false;
            
            defBtn.setTitle("A carbon footprint is the total amount of greenhouse gases, including carbon dioxide and methane, that are generated by our actions.", for: .normal)
            defBtn.titleLabel?.font = UIFont(name: "AvenirNext-Demibold", size: 14)
            
            UIView.transition(with: defBtn, duration: 0.3, options: .transitionFlipFromLeft, animations: nil, completion: nil)
        }else{
            isOpen = true;
            let text = "What is a Carbon Footprint?"
            defBtn.setTitle(text, for: .normal)
            defBtn.titleLabel?.font = UIFont(name: "AvenirNext-Bold", size: 24)
            UIView.transition(with: defBtn, duration: 0.3, options: .transitionFlipFromRight, animations: nil, completion: nil)
        }
    }
    @IBAction func effBtnTap(_ sender: Any) {
        if isOpen2{
            isOpen2 = false;
            effBtn.setTitle("Even though greenhouse gases do occur naturally, human activity contributes greatly to greenhouse gas emissions. Common activities like using electricity and driving a car emit those gases. The more those with large carbon footprints use resources, the more greenhouse gases increase and spur further climate change.", for: .normal)
            effBtn.titleLabel?.font = UIFont(name: "AvenirNext-Demibold", size: 14)
            UIView.transition(with: effBtn, duration: 0.3, options: .transitionFlipFromLeft, animations: nil, completion: nil)
        }else{
            isOpen2 = true;
            let text = "The Effect of a Large Carbon Footprint"
            effBtn.setTitle(text, for: .normal)
            effBtn.titleLabel?.font = UIFont(name: "AvenirNext-Bold", size: 24)
            UIView.transition(with: effBtn, duration: 0.3, options: .transitionFlipFromRight, animations: nil, completion: nil)
        }
        
    }
    @IBAction func statBtnTap(_ sender: Any) {
        if isOpen3{
            isOpen3 = false;
            statBtn.setTitle("- A typical U.S. household has a carbon footprint of 48 metric tons CO2e/yr.2\n- Food accounts for 10-30% of a household’s carbon footprint, usually coming from meat.\n- The average passenger car emits 0.78 pounds of CO2 per mile driven.\n- Residential electricity use in 2018 emitted 666.5 mmt CO2e, 10% of the U.S. total.", for: .normal)
            statBtn.titleLabel?.font = UIFont(name: "AvenirNext-Demibold", size: 14)
            UIView.transition(with: statBtn, duration: 0.3, options: .transitionFlipFromLeft, animations: nil, completion: nil)
        }else{
            isOpen3 = true;
            let text = "Carbon Footprint Statistics in the United States"
            statBtn.setTitle(text, for: .normal)
            statBtn.titleLabel?.font = UIFont(name: "AvenirNext-Bold", size: 24)
            UIView.transition(with: statBtn, duration: 0.3, options: .transitionFlipFromRight, animations: nil, completion: nil)
        }
    }
    
    func showSafariVC(for url1: String)
    {
        let url = URL(string: url1)
        let vc = SFSafariViewController(url: url!)
        present(vc, animated: true, completion: nil)
        
    }
    
    @IBAction func moreInfoIssue(_ sender: Any) {
        showSafariVC(for: "https://www.cnn.com/2019/09/08/us/carbon-footprint-facts-trnd/index.html")
        
    }
    
    @IBAction func moreTipsTap(_ sender: Any) {
        showSafariVC(for: "https://blog.arcadia.com/50-ways-reduce-carbon-footprint/")
    }
    
}
